TheWatchers/Areas/admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheWatchers.Models;
using TheWatchers.Areas.admin.Models;

namespace TheWatchers.Areas.admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: admin/Login
        public ActionResult Index()
        {
            return View();
        }
        TheWatchersEntities db = new TheWatchersEntities();
        [HttpPost]
        public void Login(string username, string password)
        {
            string pass = db.khachhangs.Where(n => n.tenkh == username).Select(n => n.matkhau).ToString();
            if (pass == password)
                {
                    Redirect("../ admin / Home / Index"); 
                }
            else
            {
                Response.StatusCode = 404;
            }
        }
       

    }
}

TheWatchers/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheWatchers.Models;

namespace TheWatchers.Controllers
{
    public class UserController : Controller
    {
        TheWatchersEntities db = new TheWatchersEntities();
        // GET: User
        public ActionResult Index()
        {
            khachhang kh = Session["Taikhoan"] as khachhang;
            return PartialView(kh);
        }
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(khachhang kh)
        {
            db.khachhangs.Add(kh);
            db.SaveChanges();
            return View();
        }
        
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(LoginModel model)
        {
            
            int username = model.username;
            string pass = model.password;
            khachhang kh = db.khachhangs.SingleOrDefault(n => n.makh == username || n.matkhau == pass);
            if (null != kh)
            {
                ViewBag.Thongbao = "Đăng nhập thành công";
                Session["Taikhoan"] = kh;
                return RedirectToAction("Index","Home");
            }
            else
            {
                ModelState.AddModelError("","Đăng nhập không thành công");
            }
            return View();
        }
        public ActionResult logOut()
        {
            Session["Taikhoan"] = null;
            return Redirect("/");
        }
        public ActionResult Info(int makh)
        {
            khachhang check_kh = db.khachhangs.Where(n => n.makh == makh).Single();
            if(null == check_kh)
            {
                ViewBag.Thongbao = "Không tìm thấy khách hàng";
                return null;
            }
            return View(check_kh);
        }
        public ActionResult Orders(int makh) 
        {
            List<donhang> check_dh = db.khachhangs.Where(n => n.makh == makh).Select(n => n.donhangs) as List<donhang>;
            if (check_dh.Count == 0)
            {
                ViewBag.Thongbao = "Không có đơn hàng";
                return null;
            }
            return PartialView(check_dh);
        }
        public ActionResult SendMail(string ToEmailAdress, string content)
        {

            return PartialView();
        }
    }
}

TheWatchers/Views/User/Index.cshtml
@model TheWatchers.Models.khachhang
@if (Model == null)
{
	<li class="nav-item">@Html.ActionLink("Đăng ký", "Register", "User", new { @class = "nav-link" })</li>
	<li class="nav-item">@Html.ActionLink("Đăng nhập", "Login", "User", new { @class = "nav-link" })</li>
}
else
{
	<li class="nav-item"><a class=" nav-link">Hi, @Model.tenkh</a></li>
	<li class="nav-item">@Html.ActionLink("Đăng xuất","logOut","User", new { @class = "nav-link" })</li>
}

TheWatchers/Views/User/Login.cshtml
@model TheWatchers.Models.LoginModel
@{
	ViewBag.Title = "Login";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Login</h2>
@Html.ValidationSummary(false, "Đăng nhập không thành công", new { @class = "text-danger" })
@using (Html.BeginForm("login", "User", FormMethod.Post))
{
	<label>Tên đăng nhập:</label>
	<br />
	@Html.TextBoxFor(Model =>Model.username, "", new { @class = "form-control" });
	<br />
	<label>Mật khẩu:</label>
	<br />
	@Html.PasswordFor(Model => Model.password, new { @class = "form-control" });
	<br />
	@Html.CheckBoxFor(Model => Model.rememberme, new { @class = "form-control" });
	<input type="submit" class="form-control btn btn-light" value="Đăng nhập" />
}

TheWatchers/Views/User/Register.cshtml
@model TheWatchers.Models.khachhang

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đăng ký</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.tenkh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenkh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenkh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.diachi_kh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.diachi_kh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.diachi_kh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.matkhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matkhau, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Đăng ký" class="btn btn-default" />
            </div>
        </div>
    </div>
}